name: food
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

assets:
  -  assets/ 
   - assets/images

dependencies:
  animate_icons: ^2.0.0
  animated_splash_screen: ^1.3.0
  bloc: ^8.1.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.2.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  flutter_svg: ^0.22.0
  font_awesome: ^5.10.1
  font_awesome_flutter: ^10.3.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  lottie: ^2.1.0
  motion_toast: ^2.6.4
  screen_utils: ^0.0.1
  searchfield: ^0.7.2
  shared_preferences: ^2.0.15
  svg_icon: ^0.0.1
  svgpath: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
